POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name" : "admin",
  "email": "truong@gmail.com",
  "password" : "admin",
  "pic": "haha"
}
### 
POST http://localhost:5000/api/auth/login
Content-Type:  application/json

{
  "name": "admin",
  "password": "admin"
}
###
POST http://localhost:5000/api/chat
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVjYWNjMzlkOTE0NWI0NTE2N2U3OTEiLCJpYXQiOjE2ODM5NjY1Njd9.q6jDNzib7elbYtlfQgSJnoSk-oLrMpBAPi3WsEokdas

{
  "userId": "645b822f4cb7bb5a5d353272"
}
###
GET http://localhost:5000/api/chat/
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVjYWNjMzlkOTE0NWI0NTE2N2U3OTEiLCJpYXQiOjE2ODM5NjY1Njd9.q6jDNzib7elbYtlfQgSJnoSk-oLrMpBAPi3WsEokdas
###
POST http://localhost:5000/api/chat/group
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVjYWNjMzlkOTE0NWI0NTE2N2U3OTEiLCJpYXQiOjE2ODM5NjY1Njd9.q6jDNzib7elbYtlfQgSJnoSk-oLrMpBAPi3WsEokdas

{
  "name": "Demo group",
  "users": "[\"645b82a14cb7bb5a5d353275\",\"645b6f2ededf0068f4e2588e\"]"
}
###
PUT http://localhost:5000/api/chat/rename
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVjYWNjMzlkOTE0NWI0NTE2N2U3OTEiLCJpYXQiOjE2ODM5NjY1Njd9.q6jDNzib7elbYtlfQgSJnoSk-oLrMpBAPi3WsEokdas

{
  "chatId":"645f4b68d4bca34ae58dc3dc",
  "chatName":"newname"
}
###
PUT http://localhost:5000/api/chat/groupAdd
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVjYWNjMzlkOTE0NWI0NTE2N2U3OTEiLCJpYXQiOjE2ODM5NjY1Njd9.q6jDNzib7elbYtlfQgSJnoSk-oLrMpBAPi3WsEokdas

{
  "chatId":"64604b0b5cdc399ed609cd52",
  "userId":"645b822f4cb7bb5a5d353274"
}
###
PUT http://localhost:5000/api/chat/groupRemove
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDVjYWNjMzlkOTE0NWI0NTE2N2U3OTEiLCJpYXQiOjE2ODM5NjY1Njd9.q6jDNzib7elbYtlfQgSJnoSk-oLrMpBAPi3WsEokdas

{
  "chatId":"64604b0b5cdc399ed609cd52",
  "userId":"645b822f4cb7bb5a5d353274"
}